# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_details',
            name='reply',
            field=models.CharField(default=False, max_length=100000),
        ),
    ]
