# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_email_details_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(default=False, max_length=100000)),
            ],
        ),
        migrations.RemoveField(
            model_name='email_details',
            name='reply',
        ),
        migrations.AddField(
            model_name='reply',
            name='comments',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mail.Email_details'),
        ),
    ]
